### ISSUE TITLE
Github workflows

### ISSUE THREAD

**Issue by bread-kwon** [bucketplace/tracker-sdk#3]
- [x] CI (lint, type check 정도)
<s>- [ ] release 시 tag name (version) 으로 publish</s>

2번째는 필요할지 고민 필요할듯
불필요하다고 생각하면 `yarn publish` 로 해결 가능

**Comment by bread-kwon** [comment]
@chip1118 
2번째는 `yarn login` 때문에 어렵지 않을까요?

**Comment by chip1118** [comment]
이거 토큰 받아서 처리할 수 있지 않을까요??
이건 yarn publish 로 가능하니 꼭 할필요는 없을 것 같아요

**Comment by bread-kwon** [comment]
ci 보통 lint, build 정도만 체크하면 되겠죠?
요즘 너무 개발 못했더니 감 떨어지면서 재밌네요.. 😱

**Comment by chip1118** [comment]
ㅋㅋㅋㅋ 넵! 그런데 lint 는 아직 작업하고 있지 않아요

**Comment by bread-kwon** [comment]
bucketplace eslint 사용하고, 추후 개발되면 버전업 하면 될 것 같아요.

**Comment by bread-kwon** [comment]
yarn berry는 `yarn publish` 가 아닌 `yarn npm publish`
